/** Portfolio projects — single source for the Work section and the chat assistant's link whitelist. */
export const projects = [
  {
    id: 1,
    title: "UrlScan Online",
    category: "Security & URL Analysis",
    tagline: "security.scan({ target: 'url' })",
    color: "from-blue-900 to-slate-900",
    url: "https://www.urlscanonline.com/",
  },
  {
    id: 2,
    title: "Homes and Rents",
    category: "Real Estate Platform",
    tagline: "platform.build({ type: 'real-estate' })",
    color: "from-emerald-900 to-slate-900",
    url: "https://www.homesandrents.com/",
  },
  {
    id: 3,
    title: "PrimeOra Realtors",
    category: "Property Management",
    tagline: "web.deploy({ niche: 'realty' })",
    color: "from-purple-900 to-slate-900",
    url: "https://www.primeorarealtors.com/",
  },
  {
    id: 4,
    title: "Fhoneify",
    category: "E-Commerce Platform",
    tagline: "commerce.init({ sector: 'tech' })",
    color: "from-orange-900 to-slate-900",
    url: "https://www.fhoneify.in/",
  },
  {
    id: 5,
    title: "Mirai Events",
    category: "Event Management",
    tagline: "events.manage({ scale: 'global' })",
    color: "from-pink-900 to-slate-900",
    url: "https://www.miraievents.com/",
  },
  {
    id: 6,
    title: "Arohana Devanahalli Square",
    category: "Real Estate Project",
    tagline: "project.launch({ category: 'property' })",
    color: "from-teal-900 to-slate-900",
    url: "https://www.arohanadevanahallisquare.com/",
  },
  {
    id: 7,
    title: "Fhonekart",
    category: "E-Commerce Platform",
    tagline: "commerce.scale({ market: 'electronics' })",
    color: "from-indigo-900 to-slate-900",
    url: "https://www.fhonekart.in/",
  },
  {
    id: 8,
    title: "Jamia UK",
    category: "Educational Institution",
    tagline: "edu.platform({ region: 'uk' })",
    color: "from-fuchsia-900 to-slate-900",
    url: "https://www.jamiauk.in/",
  },
  {
    id: 9,
    title: "Victory Academy",
    category: "Educational Platform",
    tagline: "edu.scale({ platform: 'academy' })",
    color: "from-cyan-900 to-slate-900",
    url: "https://www.victoryacademy.live/",
    image: "/victory-academy.png",
  },
] satisfies { id: number; title: string; category: string; tagline: string; color: string; url: string; image?: string }[];
